function netId(nodeID) {
  return `w_${String(nodeID).replace(/[^a-zA-Z0-9]/g, '_')}`;
}

function driverNet(graph, exprMap, targetID, pinIndex) {
  for (const edgeID of graph.incoming.get(targetID) || []) {
    const edge = graph.edges.get(edgeID);
    if (edge?.targetPinIndex === pinIndex) return exprMap.get(edge.sourceID) ?? "1'bx";
  }
  return "1'b0";
}

export function toVerilog(graph) {
  const nodes   = Array.from(graph.nodes.values());
  const inputs  = nodes.filter(n => n.type === 'INPUT');
  const outputs = nodes.filter(n => n.type === 'OUTPUT');
  const clks    = nodes.filter(n => n.type === 'CLK');
  const dffs    = nodes.filter(n => n.type === 'DFF');
  const latches = nodes.filter(n => n.type === 'SRLATCH');
  const gates   = nodes.filter(n => !['INPUT','OUTPUT','CLK','DFF','SRLATCH'].includes(n.type));

  const topoOrder = graph.topologicalSort();
  if (!topoOrder) throw new Error('Circuit has a cycle — acyclic graph required for Verilog export.');

  // Build label→safe-identifier map
  const safeName = (n) => (n.label || n.id).replace(/[^a-zA-Z0-9_]/g, '_');
  const exprMap  = new Map();

  inputs.forEach(n => exprMap.set(n.id, safeName(n)));
  clks.forEach(n   => exprMap.set(n.id, safeName(n)));

  // Input/output port names
  const inPorts  = [...inputs.map(safeName), ...clks.map(safeName)];
  const outPorts = [...outputs.map(safeName), ...dffs.map(safeName), ...latches.map(safeName)];
  const allPorts = [...inPorts, ...outPorts];

  const L = []; // output lines

  L.push(`// Generated by Circify`);
  L.push(`module circuit_top (${allPorts.join(', ')});`);
  L.push('');
  inPorts.forEach(p  => L.push(`  input  wire ${p};`));
  outPorts.forEach(p => L.push(`  output reg  ${p};`));

  // Wire declarations for gate intermediates
  const gateSet = new Set(gates.map(n => n.id));
  const gateOrder = topoOrder.filter(id => gateSet.has(id));
  if (gateOrder.length) {
    L.push('');
    L.push('  // Intermediate wires');
    gateOrder.forEach(id => L.push(`  wire ${netId(id)};`));
  }

  // Assign gates in topological order
  if (gateOrder.length) {
    L.push('');
    L.push('  // Combinational logic');
    gateOrder.forEach(id => {
      const node = graph.nodes.get(id);
      const ins  = node.inputPins.map((_, i) => driverNet(graph, exprMap, id, i));
      let expr;
      switch (node.type) {
        case 'NOT':  expr = `~${ins[0]}`; break;
        case 'BUF':  expr = ins[0]; break;
        case 'AND':  expr = `(${ins.join(' & ')})`; break;
        case 'OR':   expr = `(${ins.join(' | ')})`; break;
        case 'XOR':  expr = `(${ins.join(' ^ ')})`; break;
        case 'XNOR': expr = `~(${ins.join(' ^ ')})`; break;
        case 'NAND': expr = `~(${ins.join(' & ')})`; break;
        case 'NOR':  expr = `~(${ins.join(' | ')})`; break;
        default:     expr = "1'bx";
      }
      L.push(`  assign ${netId(id)} = ${expr};`);
      exprMap.set(id, netId(id));
    });
  }

  // Output probe assigns
  if (outputs.length) {
    L.push('');
    L.push('  // Output probes');
    outputs.forEach(n => {
      const src = driverNet(graph, exprMap, n.id, 0);
      L.push(`  assign ${safeName(n)} = ${src};`);
    });
  }

  // DFF always blocks (rising-edge triggered)
  dffs.forEach(n => {
    const clkNet = driverNet(graph, exprMap, n.id, 1);
    const dNet   = driverNet(graph, exprMap, n.id, 0);
    L.push('');
    L.push(`  // D Flip-Flop — ${n.label || n.id}`);
    L.push(`  always @(posedge ${clkNet}) begin`);
    L.push(`    ${safeName(n)} <= ${dNet};`);
    L.push('  end');
  });

  // SR Latch always blocks
  latches.forEach(n => {
    const S = driverNet(graph, exprMap, n.id, 0);
    const R = driverNet(graph, exprMap, n.id, 1);
    L.push('');
    L.push(`  // SR Latch — ${n.label || n.id}`);
    L.push(`  always @(${S} or ${R}) begin`);
    L.push(`    if      (${S} && !${R}) ${safeName(n)} <= 1'b1;`);
    L.push(`    else if (!${S} && ${R}) ${safeName(n)} <= 1'b0;`);
    L.push(`    else if (${S} && ${R})  ${safeName(n)} <= 1'bx;`);
    L.push('    // else: hold (S=0, R=0)');
    L.push('  end');
  });

  L.push('');
  L.push('endmodule');
  return L.join('\n');
}
